// <auto-generated />
namespace HomeMarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addFK_banggiachoNhaCungUng : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFK_banggiachoNhaCungUng));
        
        string IMigrationMetadata.Id
        {
            get { return "201706061139454_add-FK_banggiacho-NhaCungUng"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
