// <auto-generated />
namespace HomeMarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_database_RegistrationId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_database_RegistrationId));
        
        string IMigrationMetadata.Id
        {
            get { return "201705130852047_update_database_RegistrationId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
